### ISSUE TITLE
Error on init

### ISSUE THREAD

**Issue by simon1tan** [rpossan/autoit#23]
Ruby 2.5.3p105 on Windows 7
Error upon init 
    
    require 'autoit'
    control = AutoIt::Control.new

 C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/autoit-1.3.3/lib/autoit/control.rb:12:in `initialize': unknown OLE server: `AutoItX3.Control' (WIN32OLERuntimeError)
    HRESULT error code:0x800401f3
      Invalid class string
	from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/autoit-1.3.3/lib/autoit/control.rb:12:in `new'
	from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/autoit-1.3.3/lib/autoit/control.rb:12:in `initialize'
	from autoit.rb:3:in `new'
	from autoit.rb:3:in `<main>'

**Comment by rpossan** [comment]
Hi @simon1tan ! Thank you for the report. I found the same issue and I'm working on this right now. When it fixed, I will inform you here.

![image](https://user-images.githubusercontent.com/157130/50895573-9e912500-13ed-11e9-8dbe-41ea83a5626e.png)

**Comment by rpossan** [comment]
@simon1tan I found the reason. AutoIT libraries are required. I don't know why, but after some Windows updates, the libraries was lost.
Try to run the command:
`autoit install`
This command will ask for admin privileges and will install AutoIt DLL libraries from the directory "https://github.com/rpossan/autoit/tree/master/vendor".
Try it and please let me know if work.
Thank you!
